WARNING 2021-02-16 14:14:53,213 : object of type 'NoneType' has no len()
WARNING 2021-02-16 14:37:57,921 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:47:00,878 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:47:38,384 : HTTPSConnectionPool(host='sohu.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020041F8A730>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
WARNING 2021-02-16 15:47:55,421 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:48:33,852 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:52:09,087 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:52:36,957 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:52:48,219 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:56:31,400 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:56:56,976 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:57:16,178 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:58:13,008 : object of type 'NoneType' has no len()
WARNING 2021-02-16 15:58:55,007 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:00:23,146 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:01:30,177 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:01:52,193 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:02:02,541 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:02:20,587 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:07:35,806 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:08:13,399 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:12:04,133 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:13:15,345 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:16:26,401 : object of type 'NoneType' has no len()
WARNING 2021-02-16 16:17:17,014 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:19:52,765 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:25:21,348 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:25:56,276 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:25:58,301 : HTTPSConnectionPool(host='tmall.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
WARNING 2021-02-16 16:26:41,912 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:27:00,130 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:27:17,843 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:31:43,847 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:38:49,563 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:39:59,099 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:40:35,483 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:41:01,364 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:43:33,761 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:46:35,125 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:47:51,829 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:48:35,592 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:48:55,565 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 16:49:54,444 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 17:46:40,021 : 'NoneType' object is not subscriptable
WARNING 2021-02-16 17:56:55,753 : HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CC2BA5C910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
WARNING 2021-02-16 17:57:09,683 : 'NoneType' object is not subscriptable
ERROR 2021-02-17 10:11:10,485 : Invalid URL 'url,age,length,.,/,-,_,&,status_code,images_external,images_internal,redirections,links_external,links_internal,input_fields,same_landing_url\n': No schema supplied. Perhaps you meant http://url,age,length,.,/,-,_,&,status_code,images_external,images_internal,redirections,links_external,links_internal,input_fields,same_landing_url
?
WARNING 2021-02-17 10:11:12,575 : HTTPSConnectionPool(host='yahoo.com,9526,17,1,2,0,0,0,200,2,0,1,5,1,4,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:12,731 : HTTPSConnectionPool(host='yahoo.com,9526,17,1,2,0,0,0,200,2,0,1,5,1,4,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:12,893 : HTTPSConnectionPool(host='yahoo.com,9526,17,1,0,0,200,2,0,1,5,1,4,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:13,049 : HTTPSConnectionPool(host='yahoo.com,9526,17,1,0,0,200,2,0,1,0,6,4,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:13,211 : HTTPSConnectionPool(host='google.com,8555,18,1,0,0,200,2,1,1,3,14,8,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:13,371 : HTTPSConnectionPool(host='youtube.com,5845,19,1,0,0,200,19,0,1,0,0,2,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:13,526 : HTTPSConnectionPool(host='tmall.com,8523,17,1,0,0,200,7,0,1,0,63,5,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:13,705 : HTTPSConnectionPool(host='sohu.com,8262,16,1,0,0,404,-1,-1,-1,-1,-1,-1,-1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:13,861 : HTTPSConnectionPool(host='baidu.com,7799,17,1,0,0,200,10,12,1,0,0,17,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E45E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:14,022 : HTTPSConnectionPool(host='qq.com,no%20info,14,1,0,0,200,24,0,1,0,0,5,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:14,183 : HTTPSConnectionPool(host='taobao.com,6511,18,1,0,0,200,137,0,2,21,1044,2,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:14,339 : HTTPSConnectionPool(host='facebook.com,8725,20,1,0,0,200,1,1,1,2,45,6,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4EB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:14,501 : HTTPSConnectionPool(host='jd.com,no%20info,14,1,0,0,200,44,0,2,40,102,1,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E42E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:14,666 : HTTPSConnectionPool(host='yahoo.com,9526,17,1,0,0,200,2,0,1,0,6,4,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E45E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:14,829 : HTTPSConnectionPool(host='wikipedia.org,7339,21,1,0,0,200,1,0,1,1,321,4,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:14,987 : HTTPSConnectionPool(host='weibo.com,8004,17,1,0,0,200,85,3,2,45,103,9,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E45E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:15,147 : HTTPSConnectionPool(host='netflix.com,8498,19,1,0,0,200,5,0,2,11,19,15,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4EB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:15,307 : HTTPSConnectionPool(host='live.com,9547,16,1,0,0,200,6,0,1,22,8,0,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:15,466 : HTTPSConnectionPool(host='reddit.com,5771,18,1,0,0,200,184,0,1,17,786,1,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:15,627 : HTTPSConnectionPool(host='panda.tv,3986,16,1,0,0,200,2,0,0,1,0,0,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C332E4610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:15,785 : HTTPSConnectionPool(host='zhanqi.tv,2511,17,1,0,0,200,91,62,1,0,0,1,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C34008310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:15,945 : HTTPSConnectionPool(host='okezone.com,5207,19,1,0,0,200,2,16,1,36,425,1,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C34008340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:16,104 : HTTPSConnectionPool(host='vk.com,no%20info,14,1,0,0,200,1,0,1,0,0,35,0%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C34008310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:16,260 : HTTPSConnectionPool(host='zoom.us,6872,15,1,0,0,200,1,52,0,0,0,28,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C340080D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:16,421 : HTTPSConnectionPool(host='twitch.tv,4270,17,1,0,0,200,0,0,1,0,5,2,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C34008160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:16,579 : HTTPSConnectionPool(host='medium.com,8301,18,1,0,0,200,0,56,0,23,172,0,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C34008100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:11:16,742 : HTTPSConnectionPool(host='linkedin.com,6680,20,1,0,0,200,2,0,1,0,111,16,1%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C340081F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:19:38,288 : HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C340C0D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
WARNING 2021-02-17 10:19:38,504 : HTTPSConnectionPool(host='portale-dati-creval.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028C340CB040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
WARNING 2021-02-17 10:37:52,288 : HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CB27652550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
WARNING 2021-02-17 10:37:52,479 : HTTPSConnectionPool(host='portale-dati-creval.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CB2763CDC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
